### PR TITLE
Added quotes around tags being searched

### PR DESCRIPTION
**Pull request by ryerrabelli**

### CODE REVIEW

**Comment by ijgnd** [comment]
Thanks for your pull request. At the moment I'm very busy and will have time at the earliest in the week after July 12th. Please be patient.

**Comment by BluMist** [comment]
@ijgnd sorry to resurrect this old one, but is this still on your radar?

**Comment by ijgnd** [comment]
I know it's very late. I added this change to a test version. I use Anki 2.1.65 and Anki itself automatically removes quotes that a user (or my addon) places around tags. So at the moment I see no point in this change. Do I miss something about this pull request?

**Comment by ijgnd** [comment]
see https://github.com/ijgnd/anki__BetterSearch/commit/03a2eae6b634e78f2f8749348d68e0bfa10f474a

**Pull request closed without merging**
